version: '3.8'
services:
  springboot-app:
#    image: springboot-app
    container_name: springbootSecureApp
    build: .
    restart: always
    ports:
      - "8443:8443"
    depends_on:
      - mysqldb
#    command: sh -c './wait-for mysql_db:3306 -- npm start'
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
#    restart: always
    #    depends on
    #    volumes:
    #      -  /home/user/Desktop/db:/var/lib/mysql
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_PASSWORD: password




